name: build

on:
  push:
  pull_request:
  schedule:
    - cron: 0 1 * * MON
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    outputs:
      ubuntu_version: ${{ steps.version.outputs.version }}
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: images
      uses: ./.github/workflows/actions/docker
      with:
        image: static
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: version
      id: version
      run: |
        . /etc/os-release
        echo "version=$ID-$VERSION_ID" >> $GITHUB_OUTPUT
  build:
    needs: [prepare]
    runs-on: ${{ needs.prepare.outputs.ubuntu_version }}
    strategy:
      fail-fast: false
      matrix:
        host:
          - ${{ needs.prepare.outputs.ubuntu_version }}
        gcc:
          - 10.3.0
          - 11.2.0
          - 4.2.1
          - 5.3.0
          - 6.5.0
          - 7.5.0
          - 8.5.0
          - 9.2.0
          - 9.4.0
        target:
          - aarch64-linux-musl
          - x86_64-linux-musl
        exclude:
          - gcc: 4.2.1
          - gcc: 5.3.0
        include:
          - host: devcontainer
            gcc: 9.4.0
            target: aarch64-linux-musl
          - host: devcontainer
            gcc: 9.4.0
            target: x86_64-linux-musl
          - host: static
            gcc: 9.4.0
            target: aarch64-linux-musl
          - host: static
            gcc: 9.4.0
            target: x86_64-linux-musl
          - host: static
            gcc: 9.4.0
            target: powerpc64-linux-musl
          - host: static
            gcc: 9.4.0
            target: i386-linux-musl
          - host: static
            gcc: 9.4.0
            target: arm-linux-musleabi
          - host: static
            gcc: 9.4.0
            target: arm-linux-musleabihf
          - host: static
            gcc: 9.4.0
            target: powerpc-linux-musl
          - host: static
            gcc: 9.4.0
            target: riscv64-linux-musl
          - host: static
            gcc: 9.4.0
            target: s390x-linux-musl
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: devcontainer
      uses: ./.github/workflows/actions/devcontainer
      if: ${{ matrix.host == 'devcontainer' }}
      id: devcontainer
    - name: docker
      uses: ./.github/workflows/actions/docker
      if: ${{ matrix.host == 'static' }}
      with:
        image: static
    - name: setup
      run: |
        case "${{ matrix.host }}" in
        devcontainer)
          echo "EXEC=${{ steps.devcontainer.outputs.exec }}" >> $GITHUB_ENV
          ;;
        static)
          echo "EXEC=.github/workflows/with-docker.sh static" >> $GITHUB_ENV
          echo "::group::apt"
          sudo env PACKAGES='qemu-user' .devcontainer/apt-packages/install.sh
          ;;
        ${{ needs.prepare.outputs.ubuntu_version }})
          echo "::group::apt"
          sudo env PACKAGES='ccache qemu-user' .devcontainer/apt-packages/install.sh
          ;;
        esac
    - name: ccache
      uses: actions/cache@v3
      id: ccache
      with:
        path: .ccache
        key: ccache-${{ matrix.host }}-${{ matrix.gcc }}-${{ matrix.target}}-${{ hashFiles('Makefile','config.mak.musl') }}
        restore-keys: |
          ccache-${{ matrix.host }}-${{ matrix.gcc }}-${{ matrix.target}}
    - name: sources
      uses: actions/cache@v3
      with:
        path: musl-cross-make/sources
        key: sources-${{ matrix.gcc }}-${{ hashFiles('musl-cross-make/Makefile') }}
        restore-keys: |
          sources-${{ matrix.gcc }}
    - name: build
      run: |
        if [ ! -d .ccache ]; then
          echo "::group::ccache-init"
          ${{ env.EXEC }} make ccache-init
          echo "::endgroup::"
        fi
        if [ -d musl-cross-make/sources ]; then
          touch musl-cross-make/sources/*
        fi
        echo "::group::Apply patches"
        ${{ env.EXEC }} make patches.apply
        echo "::endgroup::"
        ${{ env.EXEC }} make config,${{ matrix.gcc }},${{ matrix.target }} STATIC=${{ matrix.host == 'static' }}
        ${{ env.EXEC }} .github/workflows/quiet.sh make build,${{ matrix.gcc }},${{ matrix.target }}
    - name: install
      run: |
        echo "::group::ccache-stat"
        ${{ env.EXEC }} make ccache-stat
        ${{ env.EXEC }} .github/workflows/quiet.sh make install,${{ matrix.gcc }},${{ matrix.target }}
        echo "::group::size"
        du -sh out/${{ matrix.gcc }}/${{ matrix.target }}
    - name: test
      run: |
        ${{ env.EXEC }} make test,${{ matrix.gcc }},${{ matrix.target }}
        if [ "${{ matrix.host }}" = static ]; then
          make test,${{ matrix.gcc }},${{ matrix.target }}
        fi
    - name: archive
      run: |
        set -x
        tar='musl-cross-${{ matrix.target }}-gcc${{ matrix.gcc }}-${{ matrix.host }}.tar'
        tar -cf $tar --owner=0 --group=0 -C out/${{ matrix.gcc }}/${{ matrix.target }} .
        xz --keep --compress -9 --threads 0 $tar
        du -sh ${tar}*
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: musl-cross-${{ matrix.target }}-gcc${{ matrix.gcc }}-${{ matrix.host }}
        path: musl-cross-${{ matrix.target }}-gcc${{ matrix.gcc }}-${{ matrix.host }}.tar.xz
  test:
    runs-on: ${{ needs.prepare.outputs.ubuntu_version }}
    needs: [prepare, build]
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        path: out.tar
    - name: setup
      run: |
        sudo env PACKAGES='qemu-user' .devcontainer/apt-packages/install.sh
    - name: Test
      run: |
        for f in out.tar/*/* ; do
          echo "::group::Testing $(basename $f)"
          ./test.sh $f out.test hello.c
        done
  release:
    runs-on: ubuntu-latest
    needs: [prepare, build, test]
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
    - uses: actions/download-artifact@v3
    - name: upload release
      uses: softprops/action-gh-release@v1
      with:
        files: '*/*-static.tar.xz'
